openapi: 3.0.3
info:
  title: Cloud Object Storage
  version: 1.0.1
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      
security:
- BearerAuth: []
tags:
- name: Authentication
- name: Bucket operations
- name: Object operations
servers:
- url: https://s3.{region}.cloud-object-storage.appdomain.cloud
  variables:
    region:
      enum:
      - us
      - eu
      - ap
      - us-south
      - us-east
      - eu-gb
      - eu-de
      - au-syd
      - jp-tok
      - ams03
      - che01
      - hkg02
      - mex01
      - mil01
      - mon01
      - osl01
      - par01
      - sjc04
      - sao01
      - seo01
      - sng01
      - tor01
      default: us
